export const ProcessCardData = () => [
    {
        id:1,
        title:'Collection(Indexing IN)',
        field1: 'MP Used:',
        field2:'',
        field3:'',
    },
    {
        id:2,
        title:'Barcoding',
        field1:'MP Used:',
        field2:'Total Files:',
        field3:'Total Images:',
    },
    {
        id:3,
        title:'Page Numbering',
        field1: 'MP Used:',
        field2:'',
        field3:'',
    },
    {
        id:4,
        title:'Preparation',
        field1:'MP Used:',
        field2:'Total Files:',
        field3:'Total Images:', 
    },
    {
        id:5,
        title:'Scanning(ADF)',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:6,
        title:'Cover Page Scanning',
        field1:'MP Used:',
        field2:'Total Files:',
        field3:'', 
    },
    {
        id:7,
        title:'Rescanning',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:8,
        title:'Image QC',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:9,
        title:'Document Classification(Flagging)',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:10,
        title:'Indexing(Data Entry)',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:11,
        title:'CBSL QA',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:12,
        title:'Ready for Customer QA',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:13,
        title:'Customer QA Done',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:14,
        title:'PDF Upload to DMS(Export)',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    {
        id:15,
        title:'Refilling of Files',
        field1:'MP Used:',
        field2:'Total Files:',
        field3:'Total Images:', 
    },
    {
        id:16,
        title:'Inventory Out',
        field1:'MP Used:',
        field2:'',
        field3:'', 
    },
    
]